### PR TITLE
Add important info to README

### PR DESCRIPTION
**Pull request by david-a-wheeler**

### CODE REVIEW

**Comment by david-a-wheeler** [comment]
@expln - I think adding this to the README will make it easier for people to understand what this code is doing :-).

**Comment by expln** [comment]
@david-a-wheeler  That's a great description of the repository. Thank you David. I made few changes directly in your pull request, I hope you don't mind? I changed one line:

from
It's written in JavaScript using the React user interface framework.
to
It's written in ReScript using the React user interface library.

**Comment by david-a-wheeler** [comment]
I certainly don't *mind*. However, most developers have never heard of ReScript, and practically all developers know about JavaScript. I suggest changing that to:

> It's written in [ReScript](https://rescript-lang.org/) (a robustly typed programming language that compiles to JavaScript) using the [React user interface library](https://react.dev/) and [Material UI Components](https://mui.com/material-ui/getting-started/overview/).

That way, someone who's never heard of ReScript, but *does* know what JavaScript is, will immediately understand the fundamentals of its tech stack. It also gives some links, and propose adding a note about the Material UI components.

Let me see if I can modify that for you, to make it easy for you to just "add".

**Comment by david-a-wheeler** [comment]
Okay, here's a new version ready for merging. It still says "ReScript", but with more information so that people who've never heard of ReScript won't be lost.

**Comment by expln** [comment]
@david-a-wheeler  Yeah, my point with mentioning of ReScript is to make more people aware of it. In fact, if not that language I would not start writing this tool :) Thanks David for composing this summary!

**Pull request merged**
